-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 20:28:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `company` DEFAULT CHARACTER SET utf8 ;
USE `company` ;

-- -----------------------------------------------------
-- Table `company`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`workers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `full name` VARCHAR(50) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`phones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(30) NOT NULL,
  `requestType` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`workers_has_phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`workers_has_phones` (
  `workers_id` BIGINT NOT NULL,
  `phones_id` BIGINT NOT NULL,
  PRIMARY KEY (`workers_id`, `phones_id`),
  INDEX `fk_workers_has_phones_phones1_idx` (`phones_id` ASC) VISIBLE,
  INDEX `fk_workers_has_phones_workers_idx` (`workers_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_has_phones_workers`
    FOREIGN KEY (`workers_id`)
    REFERENCES `company`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_has_phones_phones1`
    FOREIGN KEY (`phones_id`)
    REFERENCES `company`.`phones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
